function C = helpsymxt
% filename: helpmsymtxt.m
% Project: POFACETS
% Description:  This program contains the text displayed in the Edit 
%           Symmtery Help GUI.
% Author:  Filippos Chatzigeorgiadis
% Date: September 2004
% Place: NPS
%
C  = {'The symmetry planes of a model can be manually entered'; ...
       'using MATLAB''s array editor. Up to three symmetry planes'; ...
       'can be entered'; ...
       ' '; ...
       'For each symmetry plane three points must be entered in consecutive'; ...
       'rows in the array editor. Thus, for three symmetry planes, nine points'; ...
       'must be entered. Each row contains three columns, corresponding to the'; ...
       'x, y and z coordinates of each point. For example,'; ... 
       'a vertex located at the origin is represented as  0 0 0 and'; ...
       'a second vertex measuring fifty meters in the y-axis from the origin'; ...
       'is represented as  0 50 0.'; ...
       ' '; ...
       'The points  comprising each plane facet should  be sequentially'; ...
       'ordered in a right-hand or  counter clockwise sense  where'; ...
       'the normal to the facet is defined in a right-hand sense.'
       ' '; ...
       'If the user needs to modify the total number of vertices in'; ...
       'a model, this is accomplished by directly modifying the number'; ...
       'of rows displayed on the top of the array editor. Notice that a'; ...
       'reduction in the number of rows results in loss of all the excess'; ...
       'vertices. An increase in the number of rows results in all-zeros'; ...
       'vertices added at the bottom of the array.'; ...
       ' '; ...
       'The total number of columns must be always 3.'};