function C = helputiltxt
% filename: helputiltxt.m
% Project: POFACETS
% Description:  This program contains the text displayed in the Utilities 
%			Help GUI version 4.4.1
% Author:  Filippos Chatzigeorgiadis
% Date: September 2004  (updated 7/15 for typos)
% Place: NPS


C  = {'The Utilities GUI allows the user to perform the following functions:'; ... 
      ' '; ...   
      '1. Model File Conversion from/to Version 2.3'; ...
      '2. Model File Conversion from/to non-GUI version'; ...
      '3. Import Models from Other CAD packages'; ...
      '4. Export Models to Other CAD packages'; ...
      '5. Manage the Materials Database'; ...
      '6. Miscellaneous Utilities';...
      ' '; ... 
      ' '; ... 
      '1. Model File Conversion from/to Version 2.3'; ...
      ' '; ...
      '   a. Conversion to Version 2.3'; ...
      '      First select the name of the 3.0 version model. Model files are'; ...
      'stored in the Models directory.'; ...
      '      Then input the name of the 2.3 version directory. The directory'; ...
      'will be created within the Models directory and two files, one for'; ...
      'coordinates and one for facets will be created'; ...
      ' '; ...
      '   b. Conversion from Version 2.3'; ...
      '      First select either the coordinates.mat or the facet.mat file'; ...
      'from the 2.3 version directory'; ...
      '      Then enter the name of the model with which it will be saved'; ...
      'in the 3.0 version. Save the model in the Models directory'; ...
      ' '; ...
      ' '; ...
      '2. Model File Conversion from/to Non-GUI Version' ; ...
      ' '; ...
      '   a. Conversion to Non-GUI Version'; ...
      '      First select the name of the 3.0 version model. Model files are'; ...
      'stored in the Models directory.'; ...
      '      Then input the name of the Non-GUI Version directory. This'; ...
      'will be created within the Models directory and two files, one for'; ...
      'coordinates and one for facets will be created'; ...
      ' '; ...
      '   b. Conversion from Non-GUI Version'; ...
      '      First select either the coordinates.m or the facets.m file'; ...
      'from the Non-GUI Version directory'; ...
      '      Then enter the name of the model with which it will be saved'; ...
      'in the 3.0 version. Save the model in the Models directory'; ...
      ' '; ...
      ' '; ...
      '3. Model Import from CAD packages'; ...
      ' '; ...
      '   a. Import from ACIS Solids stereo-lithographic text format'; ...
      '      First a solid model must be created in a CAD program and saved'; ...
      'in stereo-lithographic text format. '; ...
      '      In POFACETS use this *.stl file as input. Once the conversion'; ...
      'is completed, save the resulting model file in the desired location.'; ...
      'All facets are given PEC material properties.'; ...
      ' '; ...
      '   b. Import from *.FACET and *.DEM files'; ...
      '      These files are created by the ACADS and CIFER programs'; ...
      'respectively. First select the name of the input file. Either a'; ...
      '*.facet or a *.dem file can be selected. The program will display'; ...
      'the progress of the conversion and check process. Once the process'; ...
      'is completed save the resulting model file in the Models directory'; ...
      ' '; ...
      '  c. Import from MATLAB''s PDETOOL'; ...
      '      First run the pdetool command in MATLAB. Design a surface and'; ...
      'then create its mesh by selecting Mesh, Initialize Mesh. The mesh'; ...
      'size can be adjusted by selecting Mesh, Parameters, Maximum Edge'; ...
      'Size and then Mesh, Initialize Mesh. Export the mesh by selecting'; ...
      'Mesh, Export Mesh and OK.'; ...
      '      In the MATLAB prompt enter the command: "save petfile.mat p e t"'; ...
      'The petfile.mat file will be created in your working directory'; ...
      '      In POFACETS use this file as input. Once the conversion is'; ...
      'complete, store the resulting model file in the Models directory'; ...
      ' '; ...
      '  d. Import Raw File Format'; ...
      '     This function allows the user import a raw triangle file format.'; ...
      'The format consists of object names (string) followd by N lines,'; ...
      'one line for each face in the object.  The x,y,z values of each '; ...
      'triangle node occur on a single line followed by a line feed.';...
      'CAD applications such as Rhinocerous can export raw files.';
      ' '; ...
      ' '; ...   
      '4. Model Export to CAD packages'; ...
      ' '; ...
      'The import file formats listed above can be exported.  First select';... 
      'a POFACETS model from the Models directory then follow instructions '; ...
      'as prompted.'
      ' '; ...
      '  a. Export Sterolithographic File Format'; ...
      ' '; ...
      '     This function allows the user export a stereolithographic'; ...
      'file format.  These files generally have a *.stl extension.  Only'; ...
      'the ASCII form of the file can be exported with this utility.  The '; ...
      'basic code was obtained from the Matlab Central web page.  See the ';...
      'references in utilities.m for more information.';
      ' '; ...
      '  b. Export to *.FACET and *.DEM files'; ...
      ' '; ...
      '     Select ACADS (*.facet) or DEMACO (*.dem) format. Enter the'; ...
      'name of the resulting model and the directory to be stored in.'; ...
      'The *.dem format is used by Delcross applications (Savant and Signa).'; ...
      'The *.dem extension must be changed to *.facet to be imported into'; ...
      'the Delcross applications.'; ...
      ' '; ...
      ' '; ...   
      '  c. Export Raw File Format'; ...
      ' '; ...
      '      This function allows the user to export a raw triangle file '; ...
      ' format.  See the import section for comments.';
      ' '; ...
      ' '; ... 
      '5. Edit Materials Database'; ...
      ' '; ...
      '     This function allows the user to manage the materials database'; ...
      'by adding or deleting materials and modifying their constitutive'; ...
      'parameters. More help is provided in the Materials Database'; ...
      'Management GUI.';...
      ' '; ...
      ' '; ... 
      '6. Miscellaneous'; ...
      ' '; ...
      '  a. Clean and Compress';...
      ' '; ...
      '     This function removes triangles with zero area.  Such triangles'; ...
      'occur when the BOX command is used with zero width or length to create'; ...
      'a thin plate.  The box sides have entries in the facet table. This'; ...
      'function removes these zero area facets.  Duplicate nodes will be ';...
      'left by this process, and they are not removed. The funtionality is'; ...
      'the same as the stand-alone function CleanFile.m'; ...
      ' '; ...
      '  b. Plot Surface Normals';...
      ' '; ...
      '     This function displays a model and plots the normals for each'; ...
      'facet.  The vertex and face numbers can also be displayed.  The ';...
      'tools bar of the figure can be used to zoom in or rotate the';...
      'figure for inspecting normals. Arrows may be chopped or invisible';...
      'due to axis limits.';
       ' '; ...
      '  c. Circular Polarization';...
      ' '; ...
      '     This function generates circularly polarized RCS patterns by '; ...
      'combining TM and TE linearly polarized patterns.  Either bistatic';...
      'or monostatic patterns can be plotted determined by the data in the';...
      'two files that are read. Both files must contain data for the same';...
      'frequency, pattern cut, and angle increment values.';
        ' '; ...
      '  d. Quick Range';...
      ' '; ...
      '     Quick calculation of maximum detection range based on the'; ...
      'monostatic radar range equation (RRE). Enter radar system'; ...
      'parameters when prompted in the Command window. Results'; ...
      'also appear in the Command window.'
      };