function C = helpmatdbtxt
% filename: helpmatdbtxt.m
% Project: POFACETS
% Description:  This program displays the text in the Materials 
%		Database Help Window GUI.
% Author:  Filippos Chatzigeorgiadis
% Date: September 2004
% Place: NPS
%
C  = {'The Materials Database GUI allows the user to view, edit and'; ...
      'update the database of materials tha can be applied to the facets'; ...
      'of a model'; ...
      ' ' ; ...
      'The Material listbox allows the user to select a material to view'
      'or edit. The constitutive parameters of the material, i.e.,'; ...
      ' ' ; ...    
      'relative electric permittivity'; ...
      'loss tangent'; ...
      'real part of relative magnetic permeability'; ...
      'imaginary part of relative magnetic permeability'; ...
      ' ' ; ...
      'are displayed and can be edited.'
   	  ' '; ...
      'New - this button allows the user to enter a new material in the'; ...
      'database. The name of the material and its consitutive parameters'; ...
      'are entered by the user in the GUI that appears.'; ...
      ' '; ...
      'Save and Exit - this button saves the changes to the database and'; ...
      'closes the Materials Database GUI. If the changes should not be saved,'; ...
      'the user can simply close the GUI using the button on the title bar of'; ...
      'the GUI'};