function C = helpgraphtxt
% filename: helpgraphtxt.m
% Project: POFACETS
% Description:  This program contains the text displayed in the Graphical Model Design 
%			Help GUI.
% Author:  Filippos Chatzigeorgiadis
% Date: September 2004
% Place: NPS
%
C  = {'The Graphical Model Design GUI allows a user to design a new'; ... 
      'model or make changes to an existing model using a library of'; ...
      'customizable standard shaped models which can be combined to'; ...
      'create more complex models.'; ...
      ' '; ...
      'Sphere button: creates the model of a sphere. Parameters are'; ...
      'its radius and the number of points approximating a circle.'; ...
      ' '; ...
      'Ellipoid button: creates the model of an ellipsoid. Parameters are'; ...
      'its radius in X, Y and Z and the number of points approximating a circle.'; ...
      ' '; ...
      'Cylinder button: creates the model of a cylinder. Parameters are'; ...
      'its radius, its length, the number of points approximating a circle'; ...
      'and whether the cylinder is open or closed at its bases (the user'; ...
      'must enter a Yes or No answer in the top and bottom base fields.'; ...
      ' '; ...
      'Cone button: creates the model of a cone. Parameters are'; ...
      'its radius, its height, the number of points approximating a circle'; ...
      'and whether the cylinder is open or closed at its base (the user'; ...
      'must enter a Yes or No answer in the base fields.'; ...
      ' '; ...
      'Box button: creates the model of a parallelepiped. Parameters are'; ...
      'its length, width and height, the angle between length and width'; ...
      'the angle between the height and the Z axis and the angle between'; ...
      'the projection of the heigth in the XY plane and the X axis.'; ...
      'All angles must be in degrees. A height of zero makes a thin plate.'; ...
      'A width or length of zero makes two plates on top of each other with'...
      'outward pointing normals. The zero area sides can be removed in'...
      'Utilities.'; ...
      ' '; ...
      'Ogive button: creates the model of an ogive. Parameters are its'; ...
      'radius in X, Y and Z and the number of points approximating a circle.'; ...
      ' '; ...
      'Trapezoid button: creates the model of a trapezoid.Parameters are'; ...
      'the length of the large base, the width between the large and the'; ...
      'small base, the angle between the large base and the one of the two'; ...
      'non parallel edges, the angle between the large base and the other'; ...
      'non parallel edge, and its height. All angles must be in degrees.'; ...
      'A height of zero makes a trapazoidal sheet of zero thickness.'; ...
      'A width or length of zero makes two plates on top of each other with'...
      'outward pointing normals. The zero area sides can be removed in'...
      'Utilities.'; ..
      ' '; ...
      'Load Model button: allows the user to load a pre-exisgin model.'; ...
      'Model files are stored in the Models directory.'; ...
      ' '; ...
      'Clear All button: clears all data and resets the display.'; ...
      ' '; ...
      'Attach button: enters the GUI in the Attach Mode. The existing model'; ...
      'is maintained and all new shapes created or models loaded are added'; ...
      'to the existing model. All other actions, like rotation, movement,'; ...
      'resizing, materials and comments apply only to the model being attached.'; ...
      ' '; ...
      'Rotate button: rotates the existing model in the Z, Y and X axis.'; ...
      'The user enters the desired angle in degrees for each axis.'; ...
      'In the Attach mode the rotation is applied only to the model being'; ...
      'attached'; ...
      ' '; ...
      'Move button: moves the existing model in the Z, Y and X axis.'; ...
      'The user enters the desired distance in meters for each axis.'; ...
      'In the Attach mode the movement is applied only to the model being'; ...
      'attached'; ...
      ' '; ...
      'Resize button: resized the existing model in the Z, Y and X axis.'; ...
      'The user enters the desired resizing factor in degrees for each axis.'; ...
      'In the Attach mode the resize operation is applied only to the'; ...
      'model being attached. A resizing factor greater than 1 results in'; ...
      'the increase of the target''s size, while a positive value less than'; ...
      'one results in the decrease of the target''s size'; ...
      ' '; ...
      'Add Comments button: allows the user to enter a description for'; ...
      'the model''s facets. In the Attach mode the comments are applied'; ...
      'only to the model being attached.'; ...
      ' '; ...
      'View Comments button: allows the user to view the description of'; ...
      'the model''s facets. In the Attach mode the comments displayed pertain'; ...
      'only to the model being attached.'; ...
      ' '; ...
      'Edit Material button: allows the user to change the materials for'; ...
      'the model''s facets. In the Attach mode this is applied'; ...
      'only to the model being attached.'; ...
      ' '; ...
      'View Material button: allows the user to view the materials of'; ...
      'the model''s facets. In the Attach mode the materials displayed pertain'; ...
      'only to the model being attached.'; ...
      ' '; ...
      'Edit Symmtery button: allows the user to enter symmetry planes for'; ...
      'a model. Up to three symmetry planes are allowed. In the Attach mode'; ... 
      'this button is not active.'; ...
      ' '; ...
      'View Symmetry button: allows the user to view the symmetry planes of'; ...
      'a model after their definition is complete. In the Attach mode'; ...
      'this button is not active.'; ...
      ' '; ...
      'Grid checkbox: toggles the display of the grid'; ...
      ' '; ...
      'Save Model button: allows the user to save a model.'; ...
      'In the Attach mode this button is not active.'};