function C = helppolartxt
% filename: helppolartxt.m
% Project: POFACETS
% Description:  This program contains the text displayed in the PolarGraph 
%			Help GUI.
% Author:  Filippos Chatzigeorgiadis
% Date: September 2004
% Place: NPS


C  = {'The Polar Graph GUI displays the RCS of a phi or theta cut in'; ... 
      'polar coordinates.'; ...
      'For a phi cut, angle theta scale is displayed in the lines starting at'; ... 
      'the origin. For a theta cut, the phi angle scaleis displayed by these'; ... 
      'lines. RCS scale in dbSM is displayed in the concentric circles'; ... 
      'around the origin'; ... 
      ' '; ... 
      'Initially, the graph is empty. Hit the Plot Button to activate it.'; ... 
      'The Plot button must be also pressed to make effective any change'; ... 
      'in the graph parameters (excluding the Dynamic Range).'; ... 
      ' '; ... 
      'The Dynamic Range slider is used to specify the dynamic range'; ...
      'of the graph from 10 to 120 dB in by 10 dB steps, for optimum'; ...
      'display of the RCS plot features.'; ...
      ' '; ...
      'The Theta Cut and Phi Cut sliders are activated only when both'; ...
      'angles theta and phi vary, i.e., none is constant. The user can'; ...
      'select a phi cut, in which case the value of phi will be read'; ...
      'from the phi slider and a plot versus theta will be displayed or'; ...
      'select a theta cut, in which case the value of theta will be read'; ...
      'from the theta slider and a plot versus phi will be displayed'; ...
      'Of course, in order for the plot to be displayed the Plot button'; ...
      'must be pressed after the cut and angle selections.'; ...
      ' '; ...
      'The phi and theta sliders are activated only when both'; ...
      'angles theta and phi vary, i.e., none is constant.'; ...
      'The user can select the value of theta for a theta cut or'; ...
      'the value of phi for a phi cut. The selected values appear'; ...
      'above the sliders. Notice that the value of theta slider has'; ...
      'no effect on a phi cut and vice versa. The sliders are'; ...
      'automatically compensated to display the correct range of'; ...
      'values for the phi and theta angles'};
      