function C = helpviewmattxt
% filename: helpviewmattxt.m
% Project: POFACETS
% Description:  This program contains the text displayed in the View Material
%			Help GUI.
% Author:  Filippos Chatzigeorgiadis
% Date: September 2004
% Place: NPS
%
C  = {'The View Material GUI allows a user to view and isnpect -not edit-'; ...
      'the materials or layers of materials for each facet of a model. The'; ...
      'GUI opens along with a list of the facets'' descriptions'; ...
      ' '; ...
      'NOTICE: Initial contents of the GUI are INVALID. CLICK ON THE SLIDER'; ...
      'TO ACTIVATE THE GUI CONTENTS'; ...
      ' '; ...
      'Select Facet Slider - The user can use the slider to select the facet'; ...
      'number whose materials will be displayed. The facet number is displayed'; ...
      'above the slider. The slider limits are automatically adjusted for'; ...
      'the total number of available facets. The user can consult the list'; ...
      'of facets'' descriptions to select the appropriate facet number. Any'; ...
      'change in the slider location automatically updates the contents of'; ...
      'the GUI.'; ...
      ' '; ...
      'Material Type Edit Box - Displays the Type of material or coating'; ...
      'that has been applied to the selected facet. It cannot be edited'; ...
      ' ';
      'For each layer in the facet its consitutive parameters are displayed'; ...
      'Only the appropriate number of layers is activated for each selected'; ...
      'facet number'; ...
      ' '};