function C = helpmfreqtxt
% filename: helpmfreqtxt.m
% Project: POFACETS
% Description:  This program contains the text displayed in the RCS
%           Versus Frequency Help GUI for both the monostatic and the
%           bistatic case
% Author:  Prof. David C. Jenn, Elmo E. Garrido Jr. and Filippos
% Chatzigeorgiadis
% Date: September 2004
% Place: NPS
%


C  = {'Calculate  RCS verus Frequency computes the total radar cross section of a'; ... 
      'model using either a monostatic or a bistatic radar.'; ...
      'RCS is calculated versus frequency.Scattering objects are approximated'; ...
      'by arrays of triangles (facets) and the scattered field of each'; ...
      'triangle is computed as if it were isolated and other triangles'; ...
      'were not present.   Multiple reflections, edge diffraction and'; ...
      'surface waves are not included.  Shadowing is approximately'; ... 
      'included by considering a facet to be completely illuminated or '; ...
      'completely shadowed by the incident wave.'; ...   
      ' '; ...
      'Load File -  The first step involves loading a model file. Models are'; ...
      'stored in the Models directory. Once a model is selected, its geometry is'; ...
      'displayed for inspection. When the user closes the Showmodel GUI, the'; ...
      'calculation controls in the Monostatic RCS GUI are activated.'; ...
	  ' '; ...
      'Incidence Angle (BISTATIC CASE ONLY)- The angle of incidence is'; ...
      'entered using either the slides or directly entering values in theta'; ...
      'and phi boxes. Values can range from -360 to 360 degrees, but when'; ...
      'ground is used theta can vary from -89 to 89 degrees only'; ...
      ' '; ...
      'RCS Observation angle is entered using either the slides or directly'; ...
      'entering values in theta and phi boxes. Values can range from -360'; ...
      'to 360 degrees, but when ground is used theta can vary from 0 to 89'; ...
      'degrees only'; ...
	  ' '; ...
      'Start and Ending Frequencies -  This values define the range of'; ...
      'frequencies for which the RCS will be computed. Lowest allowable'; ...
      'value is 0.1 GHz and highest is 30 GHz'
	  ' '; ...
      'Increment - defines in fractions of a GHz the increase'; ...
      'in step for the start and ending frequencies tobe used in RCS'; ...
      'calculations'; ...
      ' '; ...
      'Use Ground Plane XY - This checkbox is used to inlcude groun effects'; ...
      'on RCS calculations. The ground plane is always the XY plane, so the'; ...
      'user might need to move the target at the desired distance above the'; ...
      'ground. This must be completed prior to the RCS calculations by'; ...
      'using the Move button in the Graphical Model Design GUI. When ground'; ...
      'use is selected, the user can either define the ground as PEC or'; ...
      'specify a value for its relative electrical permittivity. Use of '; ...
      'ground limit RCS observationangle theta values from 0 to 89'; ...
      'and incidence angle theta from -89 to 89 degrees.'; ...
      ' '; ...
      'Surface Roughness - A model may be designed to have a rough surface by'; ...
      'inputting values for correlation distance and standard deviation.  These'; ...
      'parameters contribute a diffuse scattering component of the RCS and is'; ...
      'added to the coherent component.  The random deviation of the surface'; ...
      'results in diffuse scattering which yields a relatively angle dependent'; ...
      'term to the RCS.'; ...
      ' '; ...
      'Correlation Distance - This is the average distance (in meters) at which';...
      'deviations become uncorrelated.  A large correlation distance implies a';...
      'slowly varying surface error, whereas a small correlation distance is'; ...
      'associated with a rapidly varying error.';...
      ' '; ...
      'Standard Deviation - A measure of the roughness of a surface is the'; ... 
      'standard deviation of its variation about the mean value.  Typical values'; ...
      'are usually about a tenth (1/10) of the wavelength.'; ...
      ' '; ...
      'Computational parameters that may be varied are the length of the Taylor'; ...
      'series region (Lt), the number of terms in the Taylor series (Nt), and the'; ...
      'frequency/wavelength.    Default values are Lt = .05 and Nt = 5 which in'; ...
      'general give good results with relatively fast run times.'; ...
      ' '; ...
      'Print - This button Prints the Monostatic RCS GUI'; ...
      ' '; ...
      'Calculate RCS - This button begins the RCS Calculations. Initially,'; ...
      'the user selects whether surface resistivity or material consitutive'; ...
      'parameters will be used. The program displays the progress of the RCS'; ...
      'calculations. Upon their completion, the program displays the selected'; ...
      'RCS plots and prompts the user to save the RCS results. *.mat and *.m'; ...
      'formats can be selected, so that the RCS results can be used by standard'; ...
      'MATLAB commands. RCS results files can be stored in the Results'; ...
      'directory.'};