% STL to PET (points, edges triangles output)
% PET format is generated by Matlab's pdetool
% the outputs are the arrays p e t for use in Makarov's
% RWG programs (only p and t used, some minor mods may be required)
% S. Makarov, "Antenna and EM Modeling with Matlab" (Wiley, 2002)
% STL import function from Matlab Central 
% by Don Riley (www.mathworks.com downloaded 11/2009)
% this feature added by Jenn 1/2015
% uses function rndread(...) 

% STAND ALONE PROGRAM (seems to work but not thoroughly validated)

[filename, pathname]=uigetfile('*.stl','Select STL model');
fileloc=[pathname, filename];
if filename~=0
% Read the CAD data file:
[F, V, C] = rndread(fileloc);
figure(2)
clf;
  P = patch('faces', F, 'vertices' ,V);
  set(P, 'facec', 'flat');            % Set the face color flat
  set(P, 'FaceVertexCData', C);       % Set the color (from file)
  set(P, 'EdgeColor','none');         % Set the edge color
  light                               % add a default light
  daspect([1 1 1])                    % Setting the aspect ratio
  view(3)                             % Isometric view
  xlabel('X'),ylabel('Y'),zlabel('Z')
  title('Imported STL model')
  drawnow                             % axis manual
  disp(['CAD file ' fileloc ' data is read'])
  [N,M]=size(F');
  t=[F'; ones(1,M)];
  p=V';
  e=p;  % dummy array not used in RWG programs
% save variables to file
  [FILENAME, PATHNAME, FILTERINDEX] = uiputfile('*.mat','Input name of file to save data');
  if FILENAME~=0
    save([PATHNAME FILENAME],'p','e','t');
  end
   close(2)
end
    

